apiVersion: apps/v1
kind: Deployment
metadata:
  name: specialtopicsproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: videoclassifier
  template:
    metadata:
      labels:
        app: videoclassifier
    spec:
      containers:
      - name: cv-app
        image: gcr.io/specialtopicsproject/webapp:v1
        ports:
        - containerPort: 8501